# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jober/dvlpt/carnet_python/carnet_qt4.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 871)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tcombobox_1 = QtWidgets.QTabWidget(self.centralwidget)
        self.Tcombobox_1.setGeometry(QtCore.QRect(-10, 0, 681, 871))
        self.Tcombobox_1.setObjectName("Tcombobox_1")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.TCheckbutton1 = QtWidgets.QCheckBox(self.tab)
        self.TCheckbutton1.setGeometry(QtCore.QRect(10, 20, 95, 23))
        self.TCheckbutton1.setObjectName("TCheckbutton1")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.TCheckbutton1)
        self.TCheckbutton2 = QtWidgets.QCheckBox(self.tab)
        self.TCheckbutton2.setGeometry(QtCore.QRect(10, 40, 95, 23))
        self.TCheckbutton2.setObjectName("TCheckbutton2")
        self.buttonGroup.addButton(self.TCheckbutton2)
        self.TCheckbutton3 = QtWidgets.QCheckBox(self.tab)
        self.TCheckbutton3.setGeometry(QtCore.QRect(100, 20, 181, 23))
        self.TCheckbutton3.setObjectName("TCheckbutton3")
        self.buttonGroup.addButton(self.TCheckbutton3)
        self.TCheckbutton4 = QtWidgets.QCheckBox(self.tab)
        self.TCheckbutton4.setGeometry(QtCore.QRect(280, 20, 291, 23))
        self.TCheckbutton4.setObjectName("TCheckbutton4")
        self.buttonGroup.addButton(self.TCheckbutton4)
        self.TCheckbutton5 = QtWidgets.QCheckBox(self.tab)
        self.TCheckbutton5.setGeometry(QtCore.QRect(100, 40, 121, 23))
        self.TCheckbutton5.setObjectName("TCheckbutton5")
        self.buttonGroup.addButton(self.TCheckbutton5)
        self.TCheckbutton6 = QtWidgets.QCheckBox(self.tab)
        self.TCheckbutton6.setGeometry(QtCore.QRect(280, 40, 95, 23))
        self.TCheckbutton6.setObjectName("TCheckbutton6")
        self.buttonGroup.addButton(self.TCheckbutton6)
        self.Entry7 = QtWidgets.QLineEdit(self.tab)
        self.Entry7.setGeometry(QtCore.QRect(350, 40, 221, 24))
        self.Entry7.setObjectName("Entry7")
        self.Entry2 = QtWidgets.QLineEdit(self.tab)
        self.Entry2.setGeometry(QtCore.QRect(120, 80, 451, 24))
        self.Entry2.setObjectName("Entry2")
        self.Entry3 = QtWidgets.QLineEdit(self.tab)
        self.Entry3.setGeometry(QtCore.QRect(120, 120, 451, 24))
        self.Entry3.setObjectName("Entry3")
        self.Entry4 = QtWidgets.QLineEdit(self.tab)
        self.Entry4.setGeometry(QtCore.QRect(120, 160, 451, 24))
        self.Entry4.setObjectName("Entry4")
        self.Entry6 = QtWidgets.QLineEdit(self.tab)
        self.Entry6.setGeometry(QtCore.QRect(120, 190, 451, 24))
        self.Entry6.setObjectName("Entry6")
        self.Entry5 = QtWidgets.QLineEdit(self.tab)
        self.Entry5.setGeometry(QtCore.QRect(120, 230, 451, 24))
        self.Entry5.setObjectName("Entry5")
        self.Entry1 = QtWidgets.QLineEdit(self.tab)
        self.Entry1.setGeometry(QtCore.QRect(120, 270, 451, 24))
        self.Entry1.setObjectName("Entry1")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 80, 73, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 73, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 73, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 91, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 270, 73, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 350, 73, 18))
        self.label_6.setObjectName("label_6")
        self.TButton13 = QtWidgets.QPushButton(self.tab)
        self.TButton13.setGeometry(QtCore.QRect(580, 30, 93, 28))
        self.TButton13.setObjectName("TButton13")
        self.TButton2 = QtWidgets.QPushButton(self.tab)
        self.TButton2.setGeometry(QtCore.QRect(580, 80, 93, 28))
        self.TButton2.setObjectName("TButton2")
        self.TButton3 = QtWidgets.QPushButton(self.tab)
        self.TButton3.setGeometry(QtCore.QRect(580, 120, 93, 28))
        self.TButton3.setObjectName("TButton3")
        self.TButton4 = QtWidgets.QPushButton(self.tab)
        self.TButton4.setGeometry(QtCore.QRect(580, 170, 93, 28))
        self.TButton4.setObjectName("TButton4")
        self.TButton5 = QtWidgets.QPushButton(self.tab)
        self.TButton5.setGeometry(QtCore.QRect(580, 230, 93, 28))
        self.TButton5.setObjectName("TButton5")
        self.TButton1 = QtWidgets.QPushButton(self.tab)
        self.TButton1.setGeometry(QtCore.QRect(580, 270, 93, 28))
        self.TButton1.setObjectName("TButton1")
        self.TButton14 = QtWidgets.QPushButton(self.tab)
        self.TButton14.setGeometry(QtCore.QRect(580, 340, 93, 28))
        self.TButton14.setObjectName("TButton14")
        self.TButton7 = QtWidgets.QPushButton(self.tab)
        self.TButton7.setGeometry(QtCore.QRect(580, 410, 93, 28))
        self.TButton7.setObjectName("TButton7")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(170, 450, 501, 371))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Button9 = QtWidgets.QPushButton(self.tab_3)
        self.Button9.setGeometry(QtCore.QRect(370, 10, 93, 28))
        self.Button9.setObjectName("Button9")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 140, 431, 151))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.fontComboBox = QtWidgets.QFontComboBox(self.tab_3)
        self.fontComboBox.setGeometry(QtCore.QRect(40, 10, 227, 32))
        font = QtGui.QFont()
        font.setFamily("Montez")
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(20, 50, 461, 261))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(390, 10, 58, 71))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("timbre_pie_xii.gif"))
        self.label_9.setObjectName("label_9")
        self.frame.raise_()
        self.Button9.raise_()
        self.plainTextEdit.raise_()
        self.fontComboBox.raise_()
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 73, 18))
        self.label_7.setObjectName("label_7")
        self.Entry17 = QtWidgets.QLineEdit(self.tab_4)
        self.Entry17.setGeometry(QtCore.QRect(110, 20, 271, 24))
        self.Entry17.setObjectName("Entry17")
        self.Entry18 = QtWidgets.QLineEdit(self.tab_4)
        self.Entry18.setGeometry(QtCore.QRect(110, 50, 271, 24))
        self.Entry18.setText("")
        self.Entry18.setObjectName("Entry18")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 73, 18))
        self.label_8.setObjectName("label_8")
        self.Button11 = QtWidgets.QPushButton(self.tab_4)
        self.Button11.setGeometry(QtCore.QRect(390, 20, 93, 28))
        self.Button11.setObjectName("Button11")
        self.Button12 = QtWidgets.QPushButton(self.tab_4)
        self.Button12.setGeometry(QtCore.QRect(390, 50, 93, 28))
        self.Button12.setObjectName("Button12")
        self.Text3 = QtWidgets.QPlainTextEdit(self.tab_4)
        self.Text3.setGeometry(QtCore.QRect(10, 80, 471, 241))
        self.Text3.setObjectName("Text3")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.Button2 = QtWidgets.QPushButton(self.tab)
        self.Button2.setEnabled(False)
        self.Button2.setGeometry(QtCore.QRect(290, 410, 93, 28))
        self.Button2.setObjectName("Button2")
        self.Button1 = QtWidgets.QPushButton(self.tab)
        self.Button1.setGeometry(QtCore.QRect(400, 410, 93, 28))
        self.Button1.setObjectName("Button1")
        self.TButton6 = QtWidgets.QPushButton(self.tab)
        self.TButton6.setGeometry(QtCore.QRect(20, 410, 93, 28))
        self.TButton6.setObjectName("TButton6")
        self.Text1 = QtWidgets.QPlainTextEdit(self.tab)
        self.Text1.setEnabled(False)
        self.Text1.setGeometry(QtCore.QRect(20, 450, 131, 371))
        self.Text1.setObjectName("Text1")
        self.Entry8 = QtWidgets.QPlainTextEdit(self.tab)
        self.Entry8.setGeometry(QtCore.QRect(120, 310, 451, 91))
        self.Entry8.setObjectName("Entry8")
        self.Button3 = QtWidgets.QPushButton(self.tab)
        self.Button3.setGeometry(QtCore.QRect(180, 410, 93, 28))
        self.Button3.setObjectName("Button3")
        self.Tcombobox_1.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 661, 171))
        self.groupBox.setObjectName("groupBox")
        self.TCombobox1 = QtWidgets.QComboBox(self.groupBox)
        self.TCombobox1.setGeometry(QtCore.QRect(10, 20, 211, 24))
        self.TCombobox1.setObjectName("TCombobox1")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.TCombobox1.addItem("")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 50, 641, 111))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 661, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 30, 641, 161))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.TButton12 = QtWidgets.QPushButton(self.tab_2)
        self.TButton12.setGeometry(QtCore.QRect(112, 190, 101, 28))
        self.TButton12.setObjectName("TButton12")
        self.TButton8 = QtWidgets.QPushButton(self.tab_2)
        self.TButton8.setGeometry(QtCore.QRect(230, 190, 93, 28))
        self.TButton8.setObjectName("TButton8")
        self.TButton9 = QtWidgets.QPushButton(self.tab_2)
        self.TButton9.setGeometry(QtCore.QRect(340, 190, 93, 28))
        self.TButton9.setObjectName("TButton9")
        self.TButton15 = QtWidgets.QPushButton(self.tab_2)
        self.TButton15.setGeometry(QtCore.QRect(450, 190, 101, 28))
        self.TButton15.setObjectName("TButton15")
        self.TButton10 = QtWidgets.QPushButton(self.tab_2)
        self.TButton10.setGeometry(QtCore.QRect(170, 440, 151, 28))
        self.TButton10.setObjectName("TButton10")
        self.TButton11 = QtWidgets.QPushButton(self.tab_2)
        self.TButton11.setGeometry(QtCore.QRect(340, 440, 241, 28))
        self.TButton11.setObjectName("TButton11")
        self.Canvas1 = QtWidgets.QWidget(self.tab_2)
        self.Canvas1.setGeometry(QtCore.QRect(20, 490, 641, 211))
        self.Canvas1.setObjectName("Canvas1")
        self.Tcombobox_1.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Tcombobox_1.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TCheckbutton1.setText(_translate("MainWindow", "Monsieur"))
        self.TCheckbutton2.setText(_translate("MainWindow", "Madame"))
        self.TCheckbutton3.setText(_translate("MainWindow", "Monsieur et Madame"))
        self.TCheckbutton4.setText(_translate("MainWindow", "Monsieur et Madame   et leurs enfants"))
        self.TCheckbutton5.setText(_translate("MainWindow", "Mademoiselle"))
        self.TCheckbutton6.setText(_translate("MainWindow", "Autre"))
        self.label.setText(_translate("MainWindow", "Nom"))
        self.label_2.setText(_translate("MainWindow", "Prénom"))
        self.label_3.setText(_translate("MainWindow", "Adresse"))
        self.label_4.setText(_translate("MainWindow", "Code postal"))
        self.label_5.setText(_translate("MainWindow", "Ville"))
        self.label_6.setText(_translate("MainWindow", "Divers"))
        self.TButton13.setText(_translate("MainWindow", "Effacer"))
        self.TButton2.setText(_translate("MainWindow", "Effacer"))
        self.TButton3.setText(_translate("MainWindow", "Effacer"))
        self.TButton4.setText(_translate("MainWindow", "Effacer"))
        self.TButton5.setText(_translate("MainWindow", "Effacer"))
        self.TButton1.setText(_translate("MainWindow", "Effacer"))
        self.TButton14.setText(_translate("MainWindow", "Effacer"))
        self.TButton7.setText(_translate("MainWindow", "Tout effacer"))
        self.Button9.setText(_translate("MainWindow", "Imprimer"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Aperçu de l\'adresse"))
        self.label_7.setText(_translate("MainWindow", "Nom"))
        self.label_8.setText(_translate("MainWindow", "Numéro"))
        self.Button11.setText(_translate("MainWindow", "Ajouter"))
        self.Button12.setText(_translate("MainWindow", "Supprimer"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Téléphone"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Courriel"))
        self.Button2.setText(_translate("MainWindow", "Annuler"))
        self.Button1.setText(_translate("MainWindow", "Enregistrer"))
        self.TButton6.setText(_translate("MainWindow", "Chercher"))
        self.Button3.setText(_translate("MainWindow", "Supprimer"))
        self.Tcombobox_1.setTabText(self.Tcombobox_1.indexOf(self.tab), _translate("MainWindow", "Détails"))
        self.groupBox.setTitle(_translate("MainWindow", "Carnet d\'adresse"))
        self.TCombobox1.setItemText(0, _translate("MainWindow", "Toutes"))
        self.TCombobox1.setItemText(1, _translate("MainWindow", "A"))
        self.TCombobox1.setItemText(2, _translate("MainWindow", "B"))
        self.TCombobox1.setItemText(3, _translate("MainWindow", "C"))
        self.TCombobox1.setItemText(4, _translate("MainWindow", "D"))
        self.TCombobox1.setItemText(5, _translate("MainWindow", "E"))
        self.TCombobox1.setItemText(6, _translate("MainWindow", "F"))
        self.TCombobox1.setItemText(7, _translate("MainWindow", "G"))
        self.TCombobox1.setItemText(8, _translate("MainWindow", "H"))
        self.TCombobox1.setItemText(9, _translate("MainWindow", "I"))
        self.TCombobox1.setItemText(10, _translate("MainWindow", "J"))
        self.TCombobox1.setItemText(11, _translate("MainWindow", "K"))
        self.TCombobox1.setItemText(12, _translate("MainWindow", "L"))
        self.TCombobox1.setItemText(13, _translate("MainWindow", "M"))
        self.TCombobox1.setItemText(14, _translate("MainWindow", "N"))
        self.TCombobox1.setItemText(15, _translate("MainWindow", "O"))
        self.TCombobox1.setItemText(16, _translate("MainWindow", "P"))
        self.TCombobox1.setItemText(17, _translate("MainWindow", "Q"))
        self.TCombobox1.setItemText(18, _translate("MainWindow", "R"))
        self.TCombobox1.setItemText(19, _translate("MainWindow", "S"))
        self.TCombobox1.setItemText(20, _translate("MainWindow", "T"))
        self.TCombobox1.setItemText(21, _translate("MainWindow", "U"))
        self.TCombobox1.setItemText(22, _translate("MainWindow", "V"))
        self.TCombobox1.setItemText(23, _translate("MainWindow", "W"))
        self.TCombobox1.setItemText(24, _translate("MainWindow", "X"))
        self.TCombobox1.setItemText(25, _translate("MainWindow", "Y"))
        self.TCombobox1.setItemText(26, _translate("MainWindow", "Z"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Liste sélectionnée"))
        self.TButton12.setText(_translate("MainWindow", "Tout ajouter"))
        self.TButton8.setText(_translate("MainWindow", "Ajouter"))
        self.TButton9.setText(_translate("MainWindow", "Enlever"))
        self.TButton15.setText(_translate("MainWindow", "Tout enlever"))
        self.TButton10.setText(_translate("MainWindow", "Imprimer l\'aperçu"))
        self.TButton11.setText(_translate("MainWindow", "Imprimer la liste sélectionnée"))
        self.Tcombobox_1.setTabText(self.Tcombobox_1.indexOf(self.tab_2), _translate("MainWindow", "Liste"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

